@extends('layouts.app')

@section('content')
    @include('partials.navbar')
    @include('partials.hero')
    @include('partials.search-modal')
    @include('partials.feature')
    @include('partials.about')
    @include('partials.counter')
    @include('partials.service')
    @include('partials.product')
    @include('partials.blog')
    @include('partials.team')
    @include('partials.testimonial')
@endsection
